---
adj_data:
  sensor_ids_file: 307
  distance_file: PEMS04/distance.csv
  normalized_k: 0.1
  output_pkl_file: null  # null表示默认路径

traffic_data:
  data_file: PEMS04/pems04.npz
  output_npz_file: null  # null表示默认路径
  split_list:  # 划分比例：训练集、验证集、测试集
    - 6
    - 2
    - 2